### ISSUE TITLE
Link to annex for more info in more languages

### ISSUE THREAD

**Issue by jonathanmoregard** [jonathanmoregard/the-climate-initiative-website#20]
Annex: https://drive.google.com/file/d/1kzlETyG9kFkn_8Q_4Z1HkwN5wJX60OL0/view

**Comment by jonathanmoregard** [comment]
Needs translations to finish this one.

**Comment by jonathanmoregard** [comment]
Map with more annexes: https://drive.google.com/open?id=1cwk2ahfNn-zDATS6xDbX01OF3A7I3Tyi

**Comment by gunwa** [comment]
Have updated appendix-link for available language (pl, es, fr, de)
